name: PopcornSMP
version: 1.0.0
main: de.popcornsmp.popcornsmp.PopcornSMPPlugin
author: PopcornSMP
api-version: "1.21"
description: First-join random spawn and branding for PopcornSMP
commands:
  rtp:
    description: Teleportiert dich nach 3 Sekunden Wartezeit an eine zufällige Position.
    usage: /rtp
  tpa:
    description: Sendet eine Teleportanfrage an einen anderen Spieler.
    usage: /tpa <Spieler>
  tpaccept:
    description: Akzeptiert die letzte Teleportanfrage.
    usage: /tpaccept
  tpdeny:
    description: Lehnt die letzte Teleportanfrage ab.
    usage: /tpdeny
  home:
    description: Öffnet das Home-Menü oder teleportiert zu einem Home.
    usage: /home [Name]
  sethome:
    description: Setzt ein Home an deiner aktuellen Position.
    usage: /sethome <Name>
  delhome:
    description: Löscht ein bestehendes Home.
    usage: /delhome <Name>
  homes:
    description: Zeigt eine Liste all deiner Homes an.
    usage: /homes
